name: 'Qualys WAS integration with GitHub'
author: 'Kevin Nika'
description: 'A way to prefrom and output results of DAST scan in GitHub using Qualys.'
inputs:
  qualysuser:  # id of input
    description: 'Username of Qualys API account'
    required: true
  qualyspass: 
    description: 'Password of Qualys API account'
    required: true
  website:
    description: 'Website you will be preforming the DAST on'
    required: true
  project:
    description: 'Project/app name for the reports'
    required: true
  pat: 
    description: 'PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: entry 
      uses: actions/checkout@v2
      with:
       repository: kevinnika1/QualysWAS-Action
       token: ${{ inputs.pat }}
       
    - run: ${{ github.action_path }}/entrypoint.sh '${{ inputs.qualysuser }}' '${{ inputs.qualyspass }}' '${{ inputs.website }}' '${{ inputs.project }}'
      shell: bash
 
    - name: save the report outputted by DAST scan
      uses: actions/upload-artifact@v2
      with:
        name: DAST results
        path: ./reports/
    
